### ISSUE TITLE
Use of "Draft" in navigating posts

### ISSUE THREAD

**Issue by alankley** [scripting/wordlandSupport#16]
A minor issue but if I'm understanding correctly, the Left/Right arrow toolbar icons navigate to Previous and Next POST, correct?  Tooltips use the word "draft" which is confusing.  
"Edit the previous draft."
"Edit the next draft."
Replace "draft" with "post"

**Comment by scripting** [comment]
They are all drafts, only the ones that have been published are posts.

But this is good. Keep these kinds of comments coming.

**Comment by alankley** [comment]
> They are all drafts, only the ones that have been published are posts.
I have two posts published. The Previous/Next icons are showing the 2 posts published. They are not drafts.

**Comment by scripting** [comment]
Alan its not a bug. A published item is both a draft and a post according to the terminology of the software. Hope that clears it up. 😀

**Comment by scripting** [comment]
Here's the deal -- suppose you've published a document. Then you make some changes, but haven't published the changed version yet. That's why it's a draft, because you can always edit it. This is one of those times that there is no perfect answer, so I will incorporate your feedback into my thinking, but am not changing the software at this point. This was not an easy choice for me to make in the first place.
